version: "3.8"

services:
  task_manager:
    image: serk1llz/bars_project:task_manager_container
    container_name: task_manager_container
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_HOST_TEST: ${DB_HOST_TEST}
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER_TEST: ${DB_USER_TEST}
      DB_PASS_TEST: ${DB_PASS_TEST}
      DB_PORT_TEST: ${DB_PORT_TEST}
      SECRET: ${SECRET}

    restart: unless-stopped
    depends_on:
      - alembic
    networks:
      - app-network

  user_manager:
    image: serk1llz/bars_project:user_manager_container
    container_name: user_manager_container
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_HOST_TEST: ${DB_HOST_TEST}
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER_TEST: ${DB_USER_TEST}
      DB_PASS_TEST: ${DB_PASS_TEST}
      DB_PORT_TEST: ${DB_PORT_TEST}
      SECRET: ${SECRET}
    restart: unless-stopped
    depends_on:
      - alembic
    networks:
      - app-network

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - tododb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  alembic:
    image: serk1llz/bars_project:to_do_list_devops-alembic-1
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      - postgres
    restart: on-failure:5
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - task_manager
      - user_manager
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: serk1llz/bars_project:frontend_container
    container_name: frontend_container
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - task_manager
      - user_manager
    networks:
      - app-network

volumes:
  tododb-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge

