name: Сборка и отправка образов на продакшен
on:
  push:
    tags:
      - v*.*.*

jobs:
  build_and_push_frontend:
    if: contains(github.event.head_commit.message, 'frontend')
    runs-on: ubuntu-latest
    steps:
      - name: Проверить репозиторий
        uses: actions/checkout@v3

      - name: Войти в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и отправка frontend_container
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:frontend_container
          build-args: |
            REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}

  build_and_push_nginx:
    if: contains(github.event.head_commit.message, 'backend/init_db')
    runs-on: ubuntu-latest
    steps:
      - name: Проверить репозиторий
        uses: actions/checkout@v3

      - name: Войти в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и отправка nginx_container
        uses: docker/build-push-action@v2
        with:
          context: ./backend/init_db
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:to_do_list_devops-alembic-1

  build_and_push_user_manager:
    if: contains(github.event.head_commit.message, 'backend/user_manager')
    runs-on: ubuntu-latest
    steps:
      - name: Проверить репозиторий
        uses: actions/checkout@v3

      - name: Войти в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и отправка user_manager_container
        uses: docker/build-push-action@v2
        with:
          context: ./backend/user_manager/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:user_manager_container

  build_and_push_task_manager:
    if: contains(github.event.head_commit.message, 'backend/task_manager')
    runs-on: ubuntu-latest
    steps:
      - name: Проверить репозиторий
        uses: actions/checkout@v3

      - name: Войти в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка и отправка task_manager_container
        uses: docker/build-push-action@v2
        with:
          context: ./backend/task_manager/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:task_manager_container
