name: Build
on:
  push:
    branches:
      - 'develop'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context:
          - backend/init_db
          - backend/task_manager
          - backend/user_manager
          - frontend
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_PASS_TEST: ${{ secrets.DB_PASS_TEST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
      DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.4.0
        with:
          context: ${{ matrix.context }}
          push: false
          tags: user/${{ matrix.context }}:latest
