name: Build and Push Prod Images
on:
  push:
    tags:
      - v*.*.*
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for changes in frontend
        id: frontend_changes
        run: echo "::set-output name=changed::$(git diff --name-only HEAD~1 HEAD | grep -q '^frontend/' && echo true || echo false)"

      - name: Check for changes in backend/init_db
        id: nginx_changes
        run: echo "::set-output name=changed::$(git diff --name-only HEAD~1 HEAD | grep -q '^backend/init_db/' && echo true || echo false)"

      - name: Check for changes in backend/user_manager
        id: user_manager_changes
        run: echo "::set-output name=changed::$(git diff --name-only HEAD~1 HEAD | grep -q '^backend/user_manager/' && echo true || echo false)"

      - name: Check for changes in backend/task_manager
        id: task_manager_changes
        run: echo "::set-output name=changed::$(git diff --name-only HEAD~1 HEAD | grep -q '^backend/task_manager/' && echo true || echo false)"

      - name: Build and push frontend_container
        if: steps.frontend_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:frontend_container
          build-args: |
            REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}

      - name: Build and push nginx_container
        if: steps.nginx_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./backend/init_db
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:to_do_list_devops-alembic-1

      - name: Build and push user_manager_container
        if: steps.user_manager_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./backend/user_manager/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:user_manager_container

      - name: Build and push task_manager_container
        if: steps.task_manager_changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./backend/task_manager/
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:task_manager_container
