name: Test
on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_HOST_TEST: ${{ secrets.DB_HOST_TEST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_NAME_TEST: ${{ secrets.DB_NAME_TEST }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_PASS_TEST: ${{ secrets.DB_PASS_TEST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PORT_TEST: ${{ secrets.DB_PORT_TEST }}
      DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_USER_TEST: ${{ secrets.DB_USER_TEST }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run tests
        id: test_step
        run: |
          docker compose -f docker-compose-tests.yml up -d
          bash backend/check_test.sh

  telegram:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on success
        if: ${{ needs.test.result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Тесты прошли!!!

            Логи task_manager_container_test:
            ${{ steps.test_step.outputs.task_manager_container_test_logs }}

            Логи user_manager_container_test:
            ${{ steps.test_step.outputs.user_manager_container_test_logs }}

      - name: Upload task_manager_container_test logs
        if: ${{ needs.test.result == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: task_manager_container_test_logs
          path: task_manager_container_test_logs.txt

      - name: Upload user_manager_container_test logs
        if: ${{ needs.test.result == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: user_manager_container_test_logs
          path: user_manager_container_test_logs.txt


      - name: send telegram message on failure
        if: ${{ needs.test.result != 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Тесты не прошли!!!

            Логи task_manager_container_test:
            ${{ steps.test_step.outputs.task_manager_container_test_logs }}

            Логи user_manager_container_test:
            ${{ steps.test_step.outputs.user_manager_container_test_logs }}

      - name: Upload task_manager_container_test logs
        if: ${{ needs.test.result != 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: task_manager_container_test_logs
          path: task_manager_container_test_logs.txt

      - name: Upload user_manager_container_test logs
        if: ${{ needs.test.result != 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: user_manager_container_test_logs
          path: user_manager_container_test_logs.txt
